# Site settings
title: Lily Su
email: lilyxsu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dataanalyticsnyc.github.io" # the base hostname & protocol for your site

twitter_username: printing_3D
github_username: LilySu

# Build settings
markdown: kramdown
